export const FACE_ENROLLMENT_TAGS = {
  ENROLLMENT_LIST: 'MY_FACE_ENROLLMENTS',
  ENROLLMENT_DETAIL: 'MY_FACE_ENROLLMENT_DETAIL',
};

export const ENROLLMENT_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  REVOKED: 'REVOKED',
  NO_ENROLLMENT: 'NO_ENROLLMENT',
};

export const POLICY_TYPES = {
  SELF_ONLY: 'SELF_ONLY',
  SELF_WITH_APPROVAL: 'SELF_WITH_APPROVAL',
  HR_ONLY: 'HR_ONLY',
};

export const WIZARD_STEPS = {
  INTRODUCTION: 0,
  BLINK_CHALLENGE: 1,
  HEAD_TURN_LEFT: 2,
  HEAD_TURN_RIGHT: 3,
  CAPTURE_PREVIEW: 4,
  SUBMITTING: 5,
};

// Unified production metrics map matching normalized scalar math calculations
export const BIOMETRIC_BOUNDS = {
  MIN_DETECTION_SCORE: 0.80,
  MIN_BRIGHTNESS: 50,
  FACE_MIN_WIDTH: 120,
  FACE_MAX_WIDTH: 420,
  CENTER_TOLERANCE_PERCENT: 15
};